server:
  port: 8088
  max-http-header-size: 10240

guns:
  swagger-open: true                #是否开启swagger (true/false)
  kaptcha-open: false               #是否开启登录时验证码 (true/false)
  spring-session-open: false        #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒ath
  file-resouure-static: "/gunsServer/static/captured/**" #静态资源映射后缀
  file-upload-path: C:/picture/pic1/ #windows 文件上传地址 开发环境
#  file-upload-path: /opt/uploadFile/ #linux 文件上传地址 正式环境
  file-resouure-static-map: "http://localhost:8088/gunsServer/static/captured/" #静态资源映射url 本机浏览器开发环境
#  file-resouure-static-map: "http://192.168.104.191:8088/gunsServer/static/captured/" #静态资源映射url 本机连接手机开发环境
#  file-resouure-static-map: "http://10.253.8.80:8088/gunsServer/static/captured/" #静态资源映射url 正式环境


beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: assets/**,pages/**
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  resources:
      static-locations: classpath:/pages/modular/system/
mybatis-plus:
  typeAliasesPackage: cn.stylefeng.guns.modular.system.model
  mapper-locations: classpath:cn/stylefeng/guns/modular/**/mapping/*.xml

log:
  path: guns-logs